package overlay

import (
	"context"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/cretz/bine/tor"
	"github.com/pires/go-proxyproto"

	"github.com/webappsgo/redxt/src/config"
	"github.com/webappsgo/redxt/src/paths"
)

// torCommonPaths are the well-known tor install locations checked when
// cfg.Binary is empty, before falling back to $PATH. Order matches AI.md
// PART 32.1 "Tor Process Management".
var torCommonPaths = []string{
	"/usr/bin/tor",
	"/usr/sbin/tor",
	"/usr/local/bin/tor",
	"/opt/homebrew/bin/tor",
}

// statFile and lookPath indirect os.Stat / exec.LookPath so tests can fake
// binary resolution without touching the real filesystem or $PATH.
var (
	statFile = os.Stat
	lookPath = exec.LookPath
)

// resolveTorBinary locates the tor executable: an explicit cfg.Binary
// override wins, then common install locations, then $PATH. Returns an
// error when no tor binary is available - in which case Tor stays disabled
// and no port is allocated.
func resolveTorBinary(cfg *config.Tor) (string, error) {
	if cfg.Binary != "" {
		if _, err := statFile(cfg.Binary); err == nil {
			return cfg.Binary, nil
		}
		return "", fmt.Errorf("configured tor binary not found: %s", cfg.Binary)
	}
	for _, p := range torCommonPaths {
		if _, err := statFile(p); err == nil {
			return p, nil
		}
	}
	if p, err := lookPath("tor"); err == nil {
		return p, nil
	}
	return "", fmt.Errorf("tor binary not found - hidden service disabled")
}

// getTorConfig generates torrc content from cfg. The hidden service is
// declared here via the HiddenServiceDir/HiddenServicePort block - not via
// ADD_ONION. hsDir is the HiddenServiceDir; torBackendPort is the dedicated
// PROXY-protocol loopback listener the service forwards to.
//
// SocksPort/ControlPort use runtime "auto" detection - never saved or
// hardcoded. torBackendPort is a random-unused loopback port allocated once
// Tor is confirmed available.
func getTorConfig(cfg *config.Tor, hsDir string, torBackendPort int) string {
	controlConfig := "ControlPort 127.0.0.1:auto"

	var socksConfig string
	if cfg.UseNetwork || cfg.AllowUserPreference {
		socksConfig = "SocksPort auto"
	} else {
		socksConfig = "SocksPort 0"
	}

	safeLogging := "1"
	if !cfg.SafeLogging {
		safeLogging = "0"
	}

	var accountingConfig string
	if cfg.MaxMonthlyBandwidth != "" && cfg.MaxMonthlyBandwidth != "unlimited" {
		accountingConfig = fmt.Sprintf(`
# Monthly bandwidth limit
AccountingStart month 1 00:00
AccountingMax %s`, cfg.MaxMonthlyBandwidth)
	}

	return fmt.Sprintf(`
# ============================================================
# Tor Configuration - Generated by server binary
# This file is PERSISTENT - edits via admin panel are preserved
# Manual edits may be overwritten when config is saved via admin
# ============================================================

# SOCKS port for outbound connections (0 = disabled, auto = runtime port)
# NEVER uses default port 9050 - runtime detection only
%s

# Control connection
# NEVER uses default port 9051 - uses runtime localhost port on all OSes
%s

# Security Hardening
SafeLogging %s

# Circuit limits
MaxCircuitDirtiness 600

# Bandwidth limits per second (from config)
BandwidthRate %s
BandwidthBurst %s
%s

# Disable unused features - not a relay or exit
ExitRelay 0
ExitPolicy reject *:*
ORPort 0
DirPort 0

# Guard-discovery-attack defense (vanguards-lite) - built into Tor >= 0.4.7; keep enabled, never disable
VanguardsLiteEnabled 1

# Hidden service optimizations
HiddenServiceSingleHopMode 0

# Faster startup
FetchDirInfoEarly 1
FetchDirInfoExtraEarly 1

# Reduce memory usage
DisableDebuggerAttachment 1

# ============================================================
# Hidden Service (v3) - Tor generates and persists the key + hostname here
# ============================================================
HiddenServiceDir %s
HiddenServiceVersion 3
HiddenServicePort %d 127.0.0.1:%d
# Export per-rendezvous-circuit ID via HAProxy PROXY protocol (opaque token, not an IP)
HiddenServiceExportCircuitID haproxy
`, socksConfig, controlConfig, safeLogging, cfg.BandwidthRate, cfg.BandwidthBurst, accountingConfig, hsDir, cfg.VirtualPort, torBackendPort)
}

// ensureTorDirs creates {config_dir}/tor, {data_dir}/tor, and
// {data_dir}/tor/site with 0700 permissions, enforced idempotently on every
// call. Must run before torrc or any key material is written.
func ensureTorDirs(p paths.Paths) error {
	for _, dir := range []string{
		filepath.Join(p.Config, "tor"),
		filepath.Join(p.Data, "tor"),
		filepath.Join(p.Data, "tor", "site"),
	} {
		if err := ensureDir(dir); err != nil {
			return err
		}
	}
	return nil
}

// updateTorrc (over)writes torrc with the given content. Called at every
// startup to regenerate torrc from cfg (the backend port changes each run)
// and whenever the admin saves new Tor settings.
func updateTorrc(path string, content []byte) error {
	return writeSecureFile(path, content)
}

// torProcess is the subset of *tor.Tor behavior TorService depends on. It
// lets tests substitute a fake process without spawning a real tor binary.
type torProcess interface {
	EnableNetwork(ctx context.Context, wait bool) error
	Dialer(ctx context.Context, conf *tor.DialConf) (*tor.Dialer, error)
	Healthy() error
	Close() error
}

// realTorProcess adapts *tor.Tor to torProcess.
type realTorProcess struct {
	t *tor.Tor
}

func (r *realTorProcess) EnableNetwork(ctx context.Context, wait bool) error {
	return r.t.EnableNetwork(ctx, wait)
}

func (r *realTorProcess) Dialer(ctx context.Context, conf *tor.DialConf) (*tor.Dialer, error) {
	return r.t.Dialer(ctx, conf)
}

// Healthy pings the control connection, mirroring monitorTor's liveness
// check in AI.md PART 32.1 "Tor Process Monitoring".
func (r *realTorProcess) Healthy() error {
	_, err := r.t.Control.GetInfo("version")
	return err
}

func (r *realTorProcess) Close() error {
	return r.t.Close()
}

// startTorProcess starts a real dedicated tor process. Overridden in tests
// so no test ever spawns a real tor binary or touches the Tor network.
var startTorProcess = func(ctx context.Context, conf *tor.StartConf) (torProcess, error) {
	t, err := tor.Start(ctx, conf)
	if err != nil {
		return nil, err
	}
	return &realTorProcess{t: t}, nil
}

// TorService manages one running Tor hidden service and, optionally, its
// outbound dialer. Server binary fully owns and controls the Tor process
// lifecycle through this type.
type TorService struct {
	proc           torProcess
	onionAddress   string
	torBackendPort int
	dialer         *tor.Dialer
}

// OnionAddress returns the full .onion address.
func (s *TorService) OnionAddress() string { return s.onionAddress }

// BackendPort returns the dedicated loopback port the hidden service
// forwards to. Pass it to NewTorBackendListener.
func (s *TorService) BackendPort() int { return s.torBackendPort }

// OutboundEnabled returns true if Tor outbound connections are available.
func (s *TorService) OutboundEnabled() bool { return s.dialer != nil }

// GetHTTPClient returns an HTTP client, optionally routed through Tor.
// useTor: true = route through Tor's SOCKS5 proxy, false = direct connection.
func (s *TorService) GetHTTPClient(useTor bool) *http.Client {
	if !useTor || s.dialer == nil {
		return &http.Client{Timeout: 30 * time.Second}
	}
	return &http.Client{
		Timeout: 60 * time.Second,
		Transport: &http.Transport{
			DialContext: s.dialer.DialContext,
		},
	}
}

// HealthCheck pings the Tor control connection. The caller registers this
// as the tor_health scheduler task; this package never imports
// src/scheduler or registers anything itself.
func (s *TorService) HealthCheck(context.Context) error {
	if s.proc == nil {
		return fmt.Errorf("tor not running")
	}
	return s.proc.Healthy()
}

// Close shuts down the Tor process.
func (s *TorService) Close() error {
	if s.proc != nil {
		return s.proc.Close()
	}
	return nil
}

// NewTorBackendListener creates the dedicated PROXY-protocol loopback
// listener Tor's hidden service forwards to. Because torrc sets
// HiddenServiceExportCircuitID haproxy, Tor prepends a HAProxy PROXY v1
// header to every backend connection, so this listener - and only this
// listener - must be wrapped with go-proxyproto. It is a separate listener
// from the clearnet HTTP port. Pass svc.BackendPort() as port.
func NewTorBackendListener(port int) (net.Listener, error) {
	ln, err := net.Listen("tcp", fmt.Sprintf("127.0.0.1:%d", port))
	if err != nil {
		return nil, fmt.Errorf("listen tor backend port %d: %w", port, err)
	}
	return &proxyproto.Listener{Listener: ln}, nil
}

// startDedicatedTor resolves the tor binary first; if none is found it
// returns an error and NO backend port is allocated (Tor stays disabled).
// Otherwise it allocates a dedicated PROXY-protocol-aware loopback listener
// port, regenerates torrc, starts a dedicated tor process, waits for
// bootstrap, and reads the .onion from the HiddenServiceDir hostname file.
// Hidden service is ALWAYS enabled if a tor binary is found - no toggle.
func startDedicatedTor(ctx context.Context, cfg *config.Tor, p paths.Paths, log Logger, debugMode bool) (*TorService, error) {
	log = orDiscard(log)

	torBinary, err := resolveTorBinary(cfg)
	if err != nil {
		log.Infof("Tor binary not found, hidden service disabled: %v", err)
		return nil, err
	}

	if err := ensureTorDirs(p); err != nil {
		return nil, fmt.Errorf("failed to create tor directories: %w", err)
	}

	// Allocate the dedicated PROXY-protocol loopback port only now that Tor
	// is confirmed available. Not persisted: a fresh port each run.
	torBackendPort := config.RandomUnusedPort()

	torrcPath := filepath.Join(p.Config, "tor", "torrc")
	torDataDir := filepath.Join(p.Data, "tor")
	hsDir := filepath.Join(p.Data, "tor", "site")
	hostnamePath := filepath.Join(hsDir, "hostname")

	torrcContent := getTorConfig(cfg, hsDir, torBackendPort)
	if err := updateTorrc(torrcPath, []byte(torrcContent)); err != nil {
		return nil, fmt.Errorf("failed to write torrc: %w", err)
	}
	log.Infof("Regenerated torrc at %s (backend port %d)", torrcPath, torBackendPort)

	conf := &tor.StartConf{
		TorrcFile:       torrcPath,
		DataDir:         torDataDir,
		NoAutoSocksPort: true,
		ExePath:         torBinary,
	}

	log.Infof("Starting Tor hidden service...")
	proc, err := startTorProcess(ctx, conf)
	if err != nil {
		log.Warnf("Tor: %v", err)
		return nil, fmt.Errorf("failed to start dedicated tor: %w", err)
	}

	bootstrapTimeout := time.Duration(cfg.BootstrapTimeout) * time.Second
	dialCtx, cancel := context.WithTimeout(ctx, bootstrapTimeout)
	defer cancel()

	// Console output rule: silent during bootstrap; only after 30s of no
	// progress do we surface "Tor: connecting..." on the console.
	slowTimer := time.AfterFunc(30*time.Second, func() {
		log.Infof("Tor: connecting...")
	})
	enableErr := proc.EnableNetwork(dialCtx, true)
	slowTimer.Stop()
	if enableErr != nil {
		proc.Close()
		log.Warnf("Tor: bootstrap failed: %v", enableErr)
		return nil, fmt.Errorf("failed to enable tor network: %w", enableErr)
	}

	// The hidden service is already declared in torrc (HiddenServiceDir
	// block). Tor generated (or loaded) the v3 ed25519 key during bootstrap
	// and wrote the .onion into {hsDir}/hostname - no ADD_ONION here.
	onionBytes, err := os.ReadFile(hostnamePath)
	if err != nil {
		proc.Close()
		return nil, fmt.Errorf("failed to read onion hostname: %w", err)
	}
	onionAddress := strings.TrimSpace(string(onionBytes))

	svc := &TorService{
		proc:           proc,
		onionAddress:   onionAddress,
		torBackendPort: torBackendPort,
	}

	if cfg.UseNetwork || cfg.AllowUserPreference {
		dialer, dialerErr := proc.Dialer(ctx, nil)
		if dialerErr != nil {
			log.Warnf("Tor: failed to create outbound dialer: %v", dialerErr)
		} else {
			svc.dialer = dialer
		}
	}

	log.Infof("Tor: %s", onionAddress)
	return svc, nil
}

// ShouldUseTor determines whether outbound Tor should be used for a request,
// applying the precedence table from AI.md PART 32.1 "Tor Network for
// Outbound Connections": AllowUserPreference off, or a nil user preference,
// both fall back to the server-wide UseNetwork setting; otherwise the user
// preference wins.
func ShouldUseTor(cfg *config.Tor, userPref *bool) bool {
	if !cfg.AllowUserPreference {
		return cfg.UseNetwork
	}
	if userPref == nil {
		return cfg.UseNetwork
	}
	return *userPref
}

// TorManager owns the running TorService plus its health-monitor loop and
// handles start/restart/regenerate/apply-keys operations. Server binary
// fully owns the Tor process - starts/stops/restarts it as needed.
type TorManager struct {
	mu      sync.Mutex
	service *TorService
	config  *config.Tor
	paths   paths.Paths
	log     Logger
	ctx     context.Context
	cancel  context.CancelFunc
	wg      sync.WaitGroup
}

// NewTorManager creates a new Tor manager with the given configuration. The
// dedicated PROXY-protocol backend port is allocated inside
// startDedicatedTor (only when a tor binary is found), not by the caller.
func NewTorManager(ctx context.Context, cfg *config.Tor, p paths.Paths, log Logger) *TorManager {
	return &TorManager{
		config: cfg,
		paths:  p,
		log:    orDiscard(log),
		ctx:    ctx,
	}
}

// Start initializes Tor if a binary is found and starts the health monitor.
// Hidden service is ALWAYS enabled if a tor binary exists.
func (tm *TorManager) Start() error {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	if err := tm.startLocked(); err != nil {
		return err
	}
	tm.startMonitorLocked()
	return nil
}

// startLocked starts Tor. Must be called with mu held.
func (tm *TorManager) startLocked() error {
	service, err := startDedicatedTor(tm.ctx, tm.config, tm.paths, tm.log, false)
	if err != nil {
		return err
	}
	tm.service = service
	return nil
}

// startMonitorLocked launches the 30s-ticker health/restart loop. Must be
// called with mu held.
func (tm *TorManager) startMonitorLocked() {
	monCtx, cancel := context.WithCancel(tm.ctx)
	tm.cancel = cancel
	tm.wg.Add(1)
	go func() {
		defer tm.wg.Done()
		monitorTor(monCtx, tm)
	}()
}

// Restart stops and starts Tor (used for config changes, recovery).
func (tm *TorManager) Restart() error {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	if tm.service != nil {
		tm.service.Close()
		tm.service = nil
	}
	return tm.startLocked()
}

// UpdateConfig updates the configuration, regenerates torrc (via
// startLocked -> startDedicatedTor), and restarts Tor. Called when the
// admin saves new Tor settings via the admin panel.
func (tm *TorManager) UpdateConfig(cfg *config.Tor) error {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	tm.config = cfg
	if tm.service != nil {
		tm.service.Close()
		tm.service = nil
	}
	return tm.startLocked()
}

// RegenerateAddress deletes the persisted hidden-service key and restarts
// Tor, producing a new random .onion address.
func (tm *TorManager) RegenerateAddress() (string, error) {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	if tm.service != nil {
		tm.service.Close()
		tm.service = nil
	}
	keysDir := filepath.Join(tm.paths.Data, "tor", "site")
	if err := os.RemoveAll(keysDir); err != nil {
		return "", fmt.Errorf("failed to remove old keys: %w", err)
	}
	if err := tm.startLocked(); err != nil {
		return "", err
	}
	return tm.service.OnionAddress(), nil
}

// ApplyKeys stops Tor, writes an imported hidden-service private key, and
// restarts Tor with it.
func (tm *TorManager) ApplyKeys(privateKey []byte) (string, error) {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	if tm.service != nil {
		tm.service.Close()
		tm.service = nil
	}
	keysDir := filepath.Join(tm.paths.Data, "tor", "site")
	if err := ensureDir(keysDir); err != nil {
		return "", err
	}
	keyPath := filepath.Join(keysDir, "hs_ed25519_secret_key")
	if err := writeSecureFile(keyPath, privateKey); err != nil {
		return "", fmt.Errorf("failed to write key: %w", err)
	}
	if err := tm.startLocked(); err != nil {
		return "", err
	}
	return tm.service.OnionAddress(), nil
}

// OnionAddress returns the current .onion address (empty if not running).
func (tm *TorManager) OnionAddress() string {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	if tm.service != nil {
		return tm.service.OnionAddress()
	}
	return ""
}

// Service returns the currently running TorService, or nil.
func (tm *TorManager) Service() *TorService {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	return tm.service
}

// GetHTTPClient returns an HTTP client, optionally routed through Tor,
// falling back to a direct connection if Tor is not running.
func (tm *TorManager) GetHTTPClient(useTor bool) *http.Client {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	if tm.service != nil {
		return tm.service.GetHTTPClient(useTor)
	}
	return &http.Client{Timeout: 30 * time.Second}
}

// Close stops the health monitor and terminates the Tor process. This runs
// synchronously so the overlay process is fully stopped before a caller
// goes on to cancel the context it passed to NewTorManager.
func (tm *TorManager) Close() error {
	tm.mu.Lock()
	cancel := tm.cancel
	tm.cancel = nil
	tm.mu.Unlock()

	if cancel != nil {
		cancel()
	}
	tm.wg.Wait()

	tm.mu.Lock()
	defer tm.mu.Unlock()
	if tm.service != nil {
		err := tm.service.Close()
		tm.service = nil
		return err
	}
	return nil
}

// monitorTor is the 30s-ticker health/restart loop: it pings the Tor
// control connection and restarts an unresponsive process.
func monitorTor(ctx context.Context, tm *TorManager) {
	ticker := time.NewTicker(30 * time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			tm.checkHealth()
		}
	}
}

// checkHealth restarts the Tor process if its control connection stops
// responding.
func (tm *TorManager) checkHealth() {
	tm.mu.Lock()
	svc := tm.service
	tm.mu.Unlock()
	if svc == nil {
		return
	}
	if err := svc.HealthCheck(context.Background()); err == nil {
		return
	}
	tm.log.Warnf("Tor process unresponsive, restarting...")
	tm.mu.Lock()
	defer tm.mu.Unlock()
	if tm.service != nil {
		tm.service.Close()
		tm.service = nil
	}
	if err := tm.startLocked(); err != nil {
		tm.log.Warnf("Tor restart failed: %v", err)
	}
}
